# Generated by Django 4.1.2 on 2022-11-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0002_remove_test_allowed_tags_remove_test_num_quizzes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.quiz')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.tag')),
            ],
        ),
    ]
