# Generated by Django 4.1.1 on 2022-11-12 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0002_remove_test_allowed_tags_remove_test_num_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='review',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='QuizTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.quiz')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.tag')),
            ],
        ),
    ]
