# Generated by Django 4.1.3 on 2022-11-12 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0002_remove_test_allowed_tags_remove_test_num_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='review',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
