# Generated by Django 4.1.3 on 2022-11-15 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0002_remove_test_allowed_tags_remove_test_num_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reviewer1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reviewer2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reviewer3',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='QuizTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.quiz')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.tag')),
            ],
        ),
        migrations.CreateModel(
            name='QuizReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.quiz')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.user')),
            ],
        ),
    ]
