# Generated by Django 4.1.1 on 2022-11-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0003_quiz_approved_quiz_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='creation_date',
        ),
    ]
