# Generated by Django 4.1.3 on 2022-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0003_review_creation_date_review_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='reviewer1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='reviewer2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='reviewer3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
