# Generated by Django 4.1.3 on 2022-11-14 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moelasware", "0003_quiz_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="creation_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="review",
            name="creation_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name="QuizTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moelasware.quiz",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="moelasware.tag"
                    ),
                ),
            ],
        ),
    ]
