# Generated by Django 4.1.1 on 2022-11-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0003_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='QuizTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.quiz')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.tag')),
            ],
        ),
        migrations.CreateModel(
            name='QuizReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.quiz')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moelasware.user')),
            ],
        ),
    ]
