# Generated by Django 4.1.3 on 2022-11-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0004_quiz_reviewer1_quiz_reviewer2_quiz_reviewer3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListUnfinished',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
