# Generated by Django 4.1.3 on 2022-11-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0004_quiz_approved_quiz_creation_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizTag',
        ),
    ]
