# Generated by Django 4.1.1 on 2022-11-12 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0004_remove_quiz_approved_remove_quiz_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
