# Generated by Django 4.1.1 on 2022-11-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0004_remove_quiz_reviewer1_remove_quiz_reviewer2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
