# Generated by Django 4.1.1 on 2022-11-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0005_quiz_approved_quiz_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
