# Generated by Django 4.1.1 on 2022-11-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0005_alter_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
