# Generated by Django 4.1.3 on 2022-11-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0005_listunfinished_quiz_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='reviewer1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='reviewer2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='reviewer3',
        ),
    ]
