# Generated by Django 4.1.1 on 2022-11-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0005_delete_quiztag'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
