# Generated by Django 4.1.1 on 2022-11-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0006_review_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pending',
        ),
    ]
