# Generated by Django 4.1.1 on 2022-11-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0006_review_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
