# Generated by Django 4.1.1 on 2022-11-21 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0007_remove_review_creation_date_alter_quiz_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
