# Generated by Django 4.1.1 on 2022-11-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moelasware', '0007_remove_review_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
