version: '3'

services:
  database:
    image: postgres:15-alpine
    restart: always
    # Might need to be IDs on some systems, but there's no good way to do that in this file
    # and it would have to be manually changed
    user: $USER:$USER
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pgserverpass
      PGDATA: /var/database
    secrets:
      - pgpass
    volumes:
      - ./database:/var/database:Z
      - ./createdb.sh:/docker-entrypoint-initdb.d/createdb.sh:ro
      # Can be needed for proper directory ownership
      - /etc/passwd:/etc/passwd:ro

  backend:
    image: registry.gitlab.com/moelasware/app
    restart: always
    # wait for postgres to be listening on that por
    command: sh -c "/run/wait-for database:5432  -- ./run.sh"
    ports:
      - 4242:8000
    environment:
      DATABASE_URL: postgresql://moelasware@database:5432/moelasware?passfile=/run/secrets/pgpass
    secrets:
      - source: pgpass
        mode: 0600  # otherwise it will be ignored: https://www.postgresql.org/docs/current/libpq-pgpass.html
    # TODO: change this so it's not a volume thing; this was a somewhat lazy solution
    volumes:
      - ./wait-for:/run/wait-for:ro
    depends_on:
      - database

secrets:
  pgpass:
    file: ./.pgpass
  pgserverpass:
    file: ./.pgserverpass
