version: '3'

services:
  database:
    image: postgres:15-alpine
    restart: always
    # Might need to be IDs on some systems, but there's no good way to do that in this file
    # and it would have to be manually changed
    user: $USER:$USER
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pgpass
    secrets:
      - pgpass
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./createdb.sh:/docker-entrypoint-initdb.d/createdb.sh:ro
      # Can be needed for proper directory ownership
      - /etc/passwd:/etc/passwd:ro

  backend:
    image: registry.gitlab.com/moelasware/app
    restart: always
    ports:
      - 4242:8000
    environment:
      DATABASE_URL: postgresql://moelasware@database:5432/moelasware?passfile=/run/secrets/pgpass
    secrets:
      - pgpass
    depends_on:
      - database

secrets:
  pgpass:
    file: ./.pgpass
